spring:
  r2dbc:
    url: r2dbc:h2:mem:///test
    username: sa
    password:
    pool:
      enabled: true
logging:
  level:
    org.springframework: INFO
    org.springframework.transaction: DEBUG
    org.springframework.r2dbc: DEBUG
debug: true

