server:
  port: 8080

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/order_Demo?reWriteBatchedInserts=true
      username: postgres
      password: password
      maximum-pool-size: 10
debug: true
logging:
  level:
    org.springframework: INFO
    org.springframework.transaction: DEBUG
    org.springframework.r2dbc: DEBUG