CREATE TABLE IF NOT EXISTS PRD_PRODUCT
(
    PRODUCT_KEY BIGINT(5) NOT NULL AUTO_INCREMENT,
    PRODUCT_ID  VARCHAR(100) NOT NULL,
    name        VARCHAR(512) NOT NULL,
    PRIMARY KEY (PRODUCT_KEY)
);
